// Steps to get draftkings data
    // Find a tournament on https://www.draftkings.com/lobby#/GOLF
        // Below table select "Export to CSV"
            // Upload to Google Drive
                // Open with Sheets
                    // Build object dfsSalaries in PoolSalaries.js

// Sample

// Does not need to be Object
// {
//     year: null,
//     tournamentId: null,
//     salaries: null
// } 

// Instead just pass array and useEffect [readyToCalculateDfsSalaries] will format entire object to be stored



// Need to account for 2 WD players


export const dfsSalaries = [
    { name: "Xander Schauffele", salary: 11400 },
    { name: "Justin Thomas", salary: 10400 },
    { name: "Sungjae Im", salary: 10300 },
    { name: "Sam Burns", salary: 9800 },
    { name: "Patrick Cantlay", salary: 9600 },
    { name: "Tony Finau", salary: 9500 },
    { name: "Wyndham Clark", salary: 9400 },
    { name: "Tom Kim", salary: 9300 },
    { name: "Max Greyserman", salary: 9200 },
    { name: "Si Woo Kim", salary: 9100 },
    { name: "Cameron Young", salary: 9000 },
    { name: "Davis Thompson", salary: 8900 },
    { name: "Harry Hall", salary: 8800 },
    { name: "Kurt Kitayama", salary: 8700 },
    { name: "J.J. Spaun", salary: 8600 },
    { name: "Nick Dunlap", salary: 8500 },
    { name: "Will Zalatoris", salary: 8400 },
    { name: "Eric Cole", salary: 8300 },
    { name: "Brian Harman", salary: 8200 },
    { name: "Patrick Fishburn", salary: 8100 },
    { name: "Nick Taylor", salary: 8000 },
    { name: "Nicolas Echavarria", salary: 7900 },
    { name: "Jason Day", salary: 7900 },
    { name: "J.T. Poston", salary: 7800 },
    { name: "Ben Griffin", salary: 7800 },
    { name: "Tom Hoge", salary: 7800 },
    { name: "Denny McCarthy", salary: 7700 },
    { name: "Adam Hadwin", salary: 7700 },
    { name: "Beau Hossler", salary: 7700 },
    { name: "Cameron Davis", salary: 7600 },
    { name: "Sepp Straka", salary: 7600 },
    { name: "Christiaan Bezuidenhout", salary: 7600 },
    { name: "Jhonattan Vegas", salary: 7600 },
    { name: "Rickie Fowler", salary: 7500 },
    { name: "Lee Hodges", salary: 7500 },
    { name: "Daniel Berger", salary: 7500 },
    { name: "Kevin Yu", salary: 7500 },
    { name: "Keith Mitchell", salary: 7400 },
    { name: "Mac Meissner", salary: 7400 },
    { name: "Andrew Novak", salary: 7400 },
    { name: "Mark Hubbard", salary: 7400 },
    { name: "Bud Cauley", salary: 7300 },
    { name: "Doug Ghim", salary: 7300 },
    { name: "Billy Horschel", salary: 7300 },
    { name: "Jesper Svensson", salary: 7300 },
    { name: "Patrick Rodgers", salary: 7300 },
    { name: "Lucas Glover", salary: 7200 },
    { name: "Michael Thorbjornsen", salary: 7200 },
    { name: "Michael Kim", salary: 7200 },
    { name: "Andrew Putnam", salary: 7200 },
    { name: "Alex Smalley", salary: 7200 },
    { name: "Erik Van Rooyen", salary: 7100 },
    { name: "Harris English", salary: 7100 },
    { name: "Chan Kim", salary: 7100 },
    { name: "Mackenzie Hughes", salary: 7100 },
    { name: "Sam Stevens", salary: 7100 },
    { name: "Taylor Moore", salary: 7100 },
    { name: "Chris Kirk", salary: 7000 },
    { name: "Rico Hoey", salary: 7000 },
    { name: "Jackson Suber", salary: 7000 },
    { name: "Adam Svensson", salary: 7000 },
    { name: "Joe Highsmith", salary: 7000 },
    { name: "Ryan Gerard", salary: 7000 },
    { name: "Adam Schenk", salary: 6900 },
    { name: "Matt Kuchar", salary: 6900 },
    { name: "Justin Lower", salary: 6900 },
    { name: "Matti Schmid", salary: 6900 },
    { name: "Matthew McCarty", salary: 6900 },
    { name: "Max McGreevy", salary: 6900 },
    { name: "Victor Perez", salary: 6900 },
    { name: "Antoine Rozner", salary: 6800 },
    { name: "Chandler Phillips", salary: 6800 },
    { name: "Vince Whaley", salary: 6800 },
    { name: "Henrik Norlander", salary: 6800 },
    { name: "Greyson Sigg", salary: 6800 },
    { name: "Kevin Roy", salary: 6800 },
    { name: "Frankie Capan", salary: 6800 },
    { name: "Emiliano Grillo", salary: 6700 },
    { name: "Charley Hoffman", salary: 6700 },
    { name: "Takumi Kanaya", salary: 6700 },
    { name: "Zach Johnson", salary: 6700 },
    { name: "Jacob Bridgeman", salary: 6700 },
    { name: "Sam Ryder", salary: 6700 },
    { name: "Lanto Griffin", salary: 6700 },
    { name: "Carson Young", salary: 6700 },
    { name: "Thomas Rosenmueller", salary: 6600 },
    { name: "Ryo Hisatsune", salary: 6600 },
    { name: "Paul Peterson", salary: 6600 },
    { name: "Patton Kizzire", salary: 6600 },
    { name: "Ben Silverman", salary: 6600 },
    { name: "Wesley Bryan", salary: 6600 },
    { name: "Brian Campbell", salary: 6600 },
    { name: "Quade Cummins", salary: 6600 },
    { name: "Ben Martin", salary: 6500 },
    { name: "Aldrich Potgieter", salary: 6500 },
    { name: "Matteo Manassero", salary: 6500 },
    { name: "David Lipsky", salary: 6500 },
    { name: "Luke List", salary: 6500 },
    { name: "Nick Hardy", salary: 6500 },
    { name: "Chris Gotterup", salary: 6500 },
    { name: "Steven Fisk", salary: 6500 },
    { name: "Taylor Dickson", salary: 6500 },
    { name: "Alejandro Tosti", salary: 6400 },
    { name: "Taylor Montgomery", salary: 6400 },
    { name: "Nate Lashley", salary: 6400 },
    { name: "Joel Dahmen", salary: 6400 },
    { name: "Vincent Norrman", salary: 6400 },
    { name: "Rikuya Hoshino", salary: 6400 },
    { name: "Isaiah Salinda", salary: 6400 },
    { name: "Trevor Cone", salary: 6400 },
    { name: "Jeremy Paul", salary: 6400 },
    { name: "Brendon Todd", salary: 6300 },
    { name: "Brice Garnett", salary: 6300 },
    { name: "Jake Knapp", salary: 6300 },
    { name: "Chad Ramey", salary: 6300 },
    { name: "William Mouw", salary: 6300 },
    { name: "Ben Kohles", salary: 6300 },
    { name: "Kevin Streelman", salary: 6300 },
    { name: "Tim Widing", salary: 6300 },
    { name: "Blades Brown", salary: 6300 },
    { name: "Danny Walker", salary: 6300 },
    { name: "Kyoung-Hoon Lee", salary: 6200 },
    { name: "Chesson Hadley", salary: 6200 },
    { name: "Ricky Castillo", salary: 6200 },
    { name: "Harry Higgs", salary: 6200 },
    { name: "Kris Ventura", salary: 6200 },
    { name: "Braden Thornberry", salary: 6200 },
    { name: "Francesco Molinari", salary: 6200 },
    { name: "Trey Mullinax", salary: 6200 },
    { name: "Noah Goodwin", salary: 6200 },
    { name: "Kevin Velo", salary: 6200 },
    { name: "Will Gordon", salary: 6100 },
    { name: "David Skinns", salary: 6100 },
    { name: "Cristobal Del Solar", salary: 6100 },
    { name: "Chez Reavie", salary: 6100 },
    { name: "Danny Willett", salary: 6100 },
    { name: "Hayden Buckley", salary: 6100 },
    { name: "Brandt Snedeker", salary: 6100 },
    { name: "Sami Valimaki", salary: 6100 },
    { name: "Ryan Palmer", salary: 6100 },
    { name: "Kaito Onishi", salary: 6100 },
    { name: "Mason Andersen", salary: 6100 },
    { name: "Norman Xiong", salary: 6100 },
    { name: "Davis Riley", salary: 6000 },
    { name: "Bronson Burgoon", salary: 6000 },
    { name: "Rafael Campos", salary: 6000 },
    { name: "Matthew Riedel", salary: 6000 },
    { name: "Peter Malnati", salary: 6000 },
    { name: "Will Chandler", salary: 6000 },
    { name: "Bill Haas", salary: 6000 },
    { name: "Jason Dufner", salary: 6000 },
    { name: "John Pak", salary: 6000 },
    { name: "Kevin Kisner", salary: 6000 },
    { name: "Camilo Villegas", salary: 6000 },
    { name: "Kyle Mendoza", salary: 6000 },
    { name: "Aaron Baddeley", salary: 6000 },
    { name: "Anders Albertson", salary: 6000 },
    { name: "Philip Knowles", salary: 6000 }
];