// Steps to get draftkings data
    // Find a tournament on https://www.draftkings.com/lobby#/GOLF
        // Below table select "Export to CSV"
            // Upload to Google Drive
                // Open with Sheets
                    // Build object dfsSalaries in PoolSalaries.js

// Sample

// Does not need to be Object
// {
//     year: null,
//     tournamentId: null,
//     salaries: null
// } 

// Instead just pass array and useEffect [readyToCalculateDfsSalaries] will format entire object to be stored



// Need to account for 2 WD players

// [
//     {name: "abc", salary : 0}
// ]


export const dfsSalaries = [
    // { name: "Scottie Scheffler", salary: 12800 },
{ name: "Tommy Fleetwood", salary: 10500 },
{ name: "Ludvig Aberg", salary: 10100 },
{ name: "Robert MacIntyre", salary: 9900 },
{ name: "Russell Henley", salary: 9800 },
{ name: "Si Woo Kim", salary: 9600 },
{ name: "Jordan Spieth", salary: 9500 },
{ name: "Collin Morikawa", salary: 9400 },
{ name: "Hideki Matsuyama", salary: 9300 },
{ name: "Sepp Straka", salary: 9200 },
{ name: "Nicolai Hojgaard", salary: 9100 },
{ name: "Maverick McNealy", salary: 9000 },
{ name: "Michael Thorbjornsen", salary: 8900 },
{ name: "Rickie Fowler", salary: 8800 },
{ name: "Alex Noren", salary: 8700 },
{ name: "J.J. Spaun", salary: 8600 },
{ name: "Keith Mitchell", salary: 8500 },
{ name: "Daniel Berger", salary: 8400 },
{ name: "Ryo Hisatsune", salary: 8300 },
{ name: "Denny McCarthy", salary: 8200 },
{ name: "Sudarshan Yellamaraju", salary: 8100 },
{ name: "John Keefer", salary: 8000 },
{ name: "Nick Taylor", salary: 8000 },
{ name: "Gary Woodland", salary: 7900 },
{ name: "Brian Harman", salary: 7900 },
{ name: "Thorbjorn Olesen", salary: 7800 },
{ name: "Marco Penge", salary: 7800 },
{ name: "Jordan L. Smith", salary: 7700 },
{ name: "Ricky Castillo", salary: 7700 },
{ name: "Will Zalatoris", salary: 7600 },
{ name: "Pierceson Coody", salary: 7600 },
{ name: "Alex Smalley", salary: 7600 },
{ name: "Davis Thompson", salary: 7500 },
{ name: "Rico Hoey", salary: 7500 },
{ name: "Patrick Rodgers", salary: 7500 },
{ name: "J.T. Poston", salary: 7400 },
{ name: "Stephan Jaeger", salary: 7400 },
{ name: "Tony Finau", salary: 7400 },
{ name: "Max McGreevy", salary: 7400 },
{ name: "Matthew McCarty", salary: 7400 },
{ name: "Christiaan Bezuidenhout", salary: 7300 },
{ name: "Mac Meissner", salary: 7300 },
{ name: "Matt Wallace", salary: 7300 },
{ name: "Andrew Novak", salary: 7300 },
{ name: "Chris Kirk", salary: 7200 },
{ name: "Bud Cauley", salary: 7200 },
{ name: "Tom Kim", salary: 7200 },
{ name: "John Parry", salary: 7200 },
{ name: "Hao-Tong Li", salary: 7100 },
{ name: "Kristoffer Reitan", salary: 7100 },
{ name: "Adrien Dumont De Chassart", salary: 7100 },
{ name: "Zecheng Dou", salary: 7100 },
{ name: "Mackenzie Hughes", salary: 7100 },
{ name: "Austin Smotherman", salary: 7000 },
{ name: "Max Homa", salary: 7000 },
{ name: "William Mouw", salary: 7000 },
{ name: "Doug Ghim", salary: 7000 },
{ name: "Chad Ramey", salary: 7000 },
{ name: "Matti Schmid", salary: 7000 },
{ name: "Eric Cole", salary: 6900 },
{ name: "Michael Kim", salary: 6900 },
{ name: "Lee Hodges", salary: 6900 },
{ name: "Seonghyeon Kim", salary: 6900 },
{ name: "Seamus Power", salary: 6900 },
{ name: "Kevin Roy", salary: 6900 },
{ name: "Taylor Moore", salary: 6900 },
{ name: "Austin Eckroat", salary: 6800 },
{ name: "Beau Hossler", salary: 6800 },
{ name: "Matt Kuchar", salary: 6800 },
{ name: "Jesper Svensson", salary: 6800 },
{ name: "Billy Horschel", salary: 6800 },
{ name: "Andrew Putnam", salary: 6800 },
{ name: "Vince Whaley", salary: 6700 },
{ name: "Kevin Yu", salary: 6700 },
{ name: "Daniel Brown", salary: 6700 },
{ name: "Steven Fisk", salary: 6700 },
{ name: "A.J. Ewart", salary: 6700 },
{ name: "Emiliano Grillo", salary: 6700 },
{ name: "David Ford", salary: 6700 },
{ name: "Sami Valimaki", salary: 6600 },
{ name: "Chandler Blanchet", salary: 6600 },
{ name: "Kris Ventura", salary: 6600 },
{ name: "Jhonattan Vegas", salary: 6600 },
{ name: "Adrien Saddier", salary: 6600 },
{ name: "Bronson Burgoon", salary: 6600 },
{ name: "David Lipsky", salary: 6600 },
{ name: "Joel Dahmen", salary: 6600 },
{ name: "Carson Young", salary: 6600 },
{ name: "Webb Simpson", salary: 6500 },
{ name: "Lucas Glover", salary: 6500 },
{ name: "Garrick Higgo", salary: 6500 },
{ name: "Karl Vilips", salary: 6500 },
{ name: "Tom Hoge", salary: 6500 },
{ name: "Matthieu Pavon", salary: 6500 },
{ name: "Jimmy Stanger", salary: 6500 },
{ name: "Sam Ryder", salary: 6500 },
{ name: "Chan Kim", salary: 6500 },
{ name: "Takumi Kanaya", salary: 6400 },
{ name: "Patrick Fishburn", salary: 6400 },
{ name: "Dylan Wu", salary: 6400 },
{ name: "Zachary Bauchou", salary: 6400 },
{ name: "Brandt Snedeker", salary: 6400 },
{ name: "Mark Hubbard", salary: 6400 },
{ name: "Hank Lebioda", salary: 6400 },
{ name: "Adam Svensson", salary: 6300 },
{ name: "Davis Chatfield", salary: 6300 },
{ name: "Pontus Nyholm", salary: 6300 },
{ name: "Neal Shipley", salary: 6300 },
{ name: "Kevin Streelman", salary: 6300 },
{ name: "John VanDerLaan", salary: 6300 },
{ name: "Danny Walker", salary: 6300 },
{ name: "Joe Highsmith", salary: 6300 },
{ name: "Lanto Griffin", salary: 6300 },
{ name: "Luke Clanton", salary: 6200 },
{ name: "Erik Van Rooyen", salary: 6200 },
{ name: "Alejandro Tosti", salary: 6200 },
{ name: "Justin Lower", salary: 6200 },
{ name: "Charley Hoffman", salary: 6200 },
{ name: "Christo Lamprecht", salary: 6200 },
{ name: "Chandler Phillips", salary: 6200 },
{ name: "Paul Waring", salary: 6200 },
{ name: "Jackson Suber", salary: 6200 },
{ name: "Adam Schenk", salary: 6100 },
{ name: "Kensei Hirata", salary: 6100 },
{ name: "Peter Malnati", salary: 6100 },
{ name: "Nick Dunlap", salary: 6100 },
{ name: "Patton Kizzire", salary: 6100 },
{ name: "Brice Garnett", salary: 6100 },
{ name: "Camilo Villegas", salary: 6100 },
{ name: "Jeffrey Kang", salary: 6100 },
{ name: "Nick Hardy", salary: 6100 },
{ name: "Frankie Capan", salary: 6100 },
{ name: "Brendon Todd", salary: 6000 },
{ name: "Kyoung-Hoon Lee", salary: 6000 },
{ name: "Rafael Campos", salary: 6000 },
{ name: "Gordon Sargent", salary: 6000 },
{ name: "Marcelo Rozo", salary: 6000 },
{ name: "Ryan Palmer", salary: 6000 },
{ name: "Jimmy Walker", salary: 6000 },
{ name: "Austin Wylie", salary: 6000 },
{ name: "Charlie Crockett", salary: 6000 }
];