// Steps to get draftkings data
    // Find a tournament on https://www.draftkings.com/lobby#/GOLF
        // Below table select "Export to CSV"
            // Upload to Google Drive
                // Open with Sheets
                    // Build object dfsSalaries in PoolSalaries.js

// Sample

// Does not need to be Object
// {
//     year: null,
//     tournamentId: null,
//     salaries: null
// } 

// Instead just pass array and useEffect [readyToCalculateDfsSalaries] will format entire object to be stored



// Need to account for 2 WD players

// [
//     {name: "abc", salary : 0}
// ]


export const dfsSalaries = [
    {name: "Scottie Scheffler", salary: 12000 },
    {name: "Justin Thomas", salary: 10500 },
    {name: "Hideki Matsuyama", salary: 10200 },
    {name: "Sam Burns", salary: 10000 },
    {name: "Sungjae Im", salary: 9800 },
    {name: "Corey Conners", salary: 9700 },
    {name: "Tom Kim", salary: 9600 },
    {name: "Sahith Theegala", salary: 9500 },
    {name: "Sepp Straka", salary: 9400 },
    {name: "Rasmus Hojgaard", salary: 9200 },
    {name: "Byeong Hun An", salary: 9100 },
    {name: "Robert Macintyre", salary: 9000 },
    {name: "Kurt Kitayama", salary: 8900 },
    {name: "Maverick McNealy", salary: 8800 },
    {name: "Jordan Spieth", salary: 8700 },
    {name: "Max Greyserman", salary: 8600 },
    {name: "Wyndham Clark", salary: 8500 },
    {name: "Nick Taylor", salary: 8400 },
    {name: "Luke Clanton", salary: 8300 },
    {name: "Akshay Bhatia", salary: 8200 },
    {name: "Cameron Young", salary: 8100 },
    {name: "J.T. Poston", salary: 8000 },
    {name: "Si Woo Kim", salary: 8000 },
    {name: "J.J. Spaun", salary: 7900 },
    {name: "Min Woo Lee", salary: 7900 },
    {name: "Davis Thompson", salary: 7800 },
    {name: "Beau Hossler", salary: 7800 },
    {name: "Matt Fitzpatrick", salary: 7700 },
    {name: "Harry Hall", salary: 7700 },
    {name: "Rickie Fowler", salary: 7600 },
    {name: "Billy Horschel", salary: 7600 },
    {name: "Sam Stevens", salary: 7600 },
    {name: "Austin Eckroat", salary: 7500 },
    {name: "Keith Mitchell", salary: 7500 },
    {name: "Andrew Novak", salary: 7500 },
    {name: "Lucas Glover", salary: 7400 },
    {name: "Tom Hoge", salary: 7400 },
    {name: "Denny McCarthy", salary: 7400 },
    {name: "Daniel Berger", salary: 7400 },
    {name: "Max Homa", salary: 7300 },
    {name: "Ben Griffin", salary: 7300 },
    {name: "Thomas Detry", salary: 7300 },
    {name: "Brian Harman", salary: 7300 },
    {name: "Charley Hoffman", salary: 7200 },
    {name: "Taylor Moore", salary: 7200 },
    {name: "Seamus Power", salary: 7200 },
    {name: "Doug Ghim", salary: 7200 },
    {name: "Mark Hubbard", salary: 7200 },
    {name: "Lee Hodges", salary: 7100 },
    {name: "Matt Kuchar", salary: 7100 },
    {name: "Gary Woodland", salary: 7100 },
    {name: "Eric Cole", salary: 7100 },
    {name: "Chris Kirk", salary: 7100 },
    {name: "Nicolai Hojgaard", salary: 7000 },
    {name: "Nick Dunlap", salary: 7000 },
    {name: "Mac Meissner", salary: 7000 },
    {name: "Michael Thorbjornsen", salary: 7000 },
    {name: "Mackenzie Hughes", salary: 7000 },
    {name: "Matt Wallace", salary: 7000 },
    {name: "Patrick Rodgers", salary: 6900 },
    {name: "Ryan Fox", salary: 6900 },
    {name: "Alex Smalley", salary: 6900 },
    {name: "Adam Hadwin", salary: 6900 },
    {name: "Christiaan Bezuidenhout", salary: 6900 },
    {name: "Bud Cauley", salary: 6900 },
    {name: "Jake Knapp", salary: 6800 },
    {name: "Patrick Fishburn", salary: 6800 },
    {name: "Victor Perez", salary: 6800 },
    {name: "Nicolas Echavarria", salary: 6800 },
    {name: "Frankie Capan", salary: 6800 },
    {name: "Erik Van Rooyen", salary: 6800 },
    {name: "Max McGreevy", salary: 6800 },
    {name: "Jesper Svensson", salary: 6800 },
    {name: "C.T. Pan", salary: 6700 },
    {name: "Kevin Yu", salary: 6700 },
    {name: "Jacob Bridgeman", salary: 6700 },
    {name: "Matti Schmid", salary: 6700 },
    {name: "Michael Kim", salary: 6700 },
    {name: "Thriston Lawrence", salary: 6700 },
    {name: "Rico Hoey", salary: 6700 },
    {name: "Adam Schenk", salary: 6600 },
    {name: "Webb Simpson", salary: 6600 },
    {name: "Chan Kim", salary: 6600 },
    {name: "Andrew Putnam", salary: 6600 },
    {name: "Kyoung-Hoon Lee", salary: 6600 },
    {name: "Kris Ventura", salary: 6600 },
    {name: "Matthew McCarty", salary: 6600 },
    {name: "Adam Svensson", salary: 6500 },
    {name: "Sam Ryder", salary: 6500 },
    {name: "Joe Highsmith", salary: 6500 },
    {name: "Vince Whaley", salary: 6500 },
    {name: "Carson Young", salary: 6500 },
    {name: "Chris Gotterup", salary: 6500 },
    {name: "Lanto Griffin", salary: 6500 },
    {name: "Hayden Springer", salary: 6400 },
    {name: "Vincent Norrman", salary: 6400 },
    {name: "Greyson Sigg", salary: 6400 },
    {name: "Joel Dahmen", salary: 6400 },
    {name: "Emiliano Grillo", salary: 6400 },
    {name: "Chandler Phillips", salary: 6400 },
    {name: "Paul Waring", salary: 6400 },
    {name: "Will Gordon", salary: 6300 },
    {name: "Ben Kohles", salary: 6300 },
    {name: "Ben Silverman", salary: 6300 },
    {name: "Patton Kizzire", salary: 6300 },
    {name: "Jose Luis Ballester", salary: 6300 },
    {name: "Nick Hardy", salary: 6300 },
    {name: "Henrik Norlander", salary: 6300 },
    {name: "Steven Fisk", salary: 6300 },
    {name: "Trey Mullinax", salary: 6200 },
    {name: "Luke List", salary: 6200 },
    {name: "Ryo Hisatsune", salary: 6200 },
    {name: "Nate Lashley", salary: 6200 },
    {name: "Chad Ramey", salary: 6200 },
    {name: "Kevin Streelman", salary: 6200 },
    {name: "Ben Martin", salary: 6200 },
    {name: "Matthieu Pavon", salary: 6100 },
    {name: "Brice Garnett", salary: 6100 },
    {name: "Brendon Todd", salary: 6100 },
    {name: "Sami Valimaki", salary: 6100 },
    {name: "David Lipsky", salary: 6100 },
    {name: "Chez Reavie", salary: 6100 },
    {name: "Davis Riley", salary: 6100 },
    {name: "David Skinns", salary: 6100 },
    {name: "Will Chandler", salary: 6100 },
    {name: "Taylor Montgomery", salary: 6000 },
    {name: "Brandt Snedeker", salary: 6000 },
    {name: "Ryan Palmer", salary: 6000 },
    {name: "Camilo Villegas", salary: 6000 },
    {name: "Rafael Campos", salary: 6000 },
    {name: "Peter Malnati", salary: 6000 },
    {name: "Kevin Kisner", salary: 6000 },
    {name: "Jesse Mueller", salary: 6000 }
];